<?php
$typeArr[1] = '网站建设';
$typeArr[2] = '品牌网站建设';
$typeArr[3] = '外贸网站建设';
$typeArr[4] = '品牌营销网站';
$typeArr[5] = '商城网站建设';
$typeArr[6] = '微商网站建设';
$typeArr[7] = '新闻动态';
$typeArr[10] = '云主机';
$typeArr[11] = '经典案例';
$typeArr[12] = '营销型网站';
$typeArr[13] = '品牌网站';
$typeArr[14] = '微网站';
$typeArr[15] = '企业网站';
$typeArr[16] = '商城网站';
$typeArr[17] = '行业平台';
$typeArr[18] = '联系我们';
$typeArr[19] = '关于我们';
$typeArr[26] = '售后服务';
$typeArr[27] = '行业新闻';
$typeArr[28] = '公司新闻';
$typeArr[29] = '技术帮助';
$typeArr[30] = '其他新闻';
$typeArr[31] = '客户评价';
?>