
<field:gsmc itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gsmc>

<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:shoujihao itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shoujihao>

<field:beizhu itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:beizhu>
