[field:typename /]</h3>
					<div class="yellowTipBox tcen">经济实惠，简单小巧</div>
					<div class="t_img"><img src="http://img.dns.com.cn/host/host_pj.png"></div>
					<div class="t_cs">
						<table>
							<tr>
								<td class="ld">操作系统：</td>
								<td>Windows/Unix</td>
							</tr>
							<tr>
								<td class="ld">支持语言：</td>
								<td>asp,php,html,htm等</td>
							</tr>
							<tr>
								<td class="ld">数据库：</td>
								<td>MSSQL 50M或MYSQL 50M</td>
							</tr>
							<tr>
								<td class="ld">网页空间：</td>
								<td>200M</td>
							</tr>
							<tr>
								<td class="ld">月流量：</td>
								<td>无限制</td>
							</tr>
						</table>
					</div>
					<div class="t_price"><span class="f20 red">198</span>元/年</div>
					<div class="t_btn"><a href="[field:typelink /]" class="mybtn">查看详情</a></div>
				</div>

				<div class="host_threeItems">
					<h3>{dede:type typeid='3'}[field:typename /]</h3>
					<div class="yellowTipBox tcen">即开即用，方便快捷</div>
					<div class="t_img"><img src="http://img.dns.com.cn/host/host_bz.png"></div>
					<div class="t_cs">
						<table>
							<tr>
								<td class="ld">操作系统：</td>
								<td>Windows/Unix</td>
							</tr>
							<tr>
								<td class="ld">支持语言：</td>
								<td>asp,php,html,htm等</td>
							</tr>
							<tr>
								<td class="ld">数据库：</td>
								<td>MSSQL 100M或MYSQL 100M</td>
							</tr>
							<tr>
								<td class="ld">网页空间：</td>
								<td>500M</td>
							</tr>
							<tr>
								<td class="ld">月流量：</td>
								<td>无限制</td>
							</tr>
						</table>
					</div>
					<div class="t_price"><span class="f20 red">298</span>元/年</div>
					<div class="t_btn"><a href="[field:typelink /]" class="mybtn">查看详情</a></div>
				</div>

				<div class="host_threeItems">
					<h3>{dede:type typeid='4'}[field:typename /]</h3>
					<div class="yellowTipBox tcen">经济实惠，简单小巧</div>
					<div class="t_img"><img src="http://img.dns.com.cn/host/host_hk.png"></div>
					<div class="t_cs">
						<table>
							<tr>
								<td class="ld">操作系统：</td>
								<td>Windows/Unix</td>
							</tr>
							<tr>
								<td class="ld">支持语言：</td>
								<td>asp,php,html,htm等</td>
							</tr>
							<tr>
								<td class="ld">数据库：</td>
								<td>MSSQL 150M或MYSQL 150M</td>
							</tr>
							<tr>
								<td class="ld">网页空间：</td>
								<td>800M</td>
							</tr>
							<tr>
								<td class="ld">月流量：</td>
								<td>无限制</td>
							</tr>
						</table>
					</div>
					<div class="t_price"><span class="f20 red">398</span>元/年</div>
					<div class="t_btn"><a href="[field:typelink /]" class="mybtn">查看详情</a></div>
				</div>

				<div class="host_threeItems">
					<h3>{dede:type typeid='5'}[field:typename /]</h3>
					<div class="yellowTipBox tcen">即开即用，方便快捷</div>
					<div class="t_img"><img src="http://img.dns.com.cn/host/host_hk.png"></div>
					<div class="t_cs">
						<table>
							<tr>
								<td class="ld">操作系统：</td>
								<td>Windows/Unix</td>
							</tr>
							<tr>
								<td class="ld">支持语言：</td>
								<td>asp,php,html,htm等</td>
							</tr>
							<tr>
								<td class="ld">数据库：</td>
								<td>MSSQL 300M或MYSQL 300M</td>
							</tr>
							<tr>
								<td class="ld">网页空间：</td>
								<td>1500M</td>
							</tr>
							<tr>
								<td class="ld">月流量：</td>
								<td>无限制</td>
							</tr>
						</table>
					</div>
					<div class="t_price"><span class="f20 red">598</span>元/年</div>
					<div class="t_btn"><a href="[field:typelink /]" class="mybtn">查看详情</a></div>
				</div>
				<div class="host_threeItems Items2">
					<h3>{dede:type typeid='6'}[field:typename /]</h3>
					<div class="yellowTipBox tcen">即开即用，方便快捷</div>
					<div class="t_img"><img src="http://img.dns.com.cn/host/host_hk.png"></div>
					<div class="t_cs">
						<table>
							<tr>
								<td class="ld">操作系统：</td>
								<td>Windows/Unix</td>
							</tr>
							<tr>
								<td class="ld">支持语言：</td>
								<td>asp,php,html,htm等</td>
							</tr>
							<tr>
								<td class="ld">数据库：</td>
								<td>MSSQL 300M或MYSQL 300M</td>
							</tr>
							<tr>
								<td class="ld">网页空间：</td>
								<td>1500M</td>
							</tr>
							<tr>
								<td class="ld">月流量：</td>
								<td>无限制</td>
							</tr>
						</table>
					</div>
					<div class="t_price"><span class="f20 red">598</span>元/年</div>
					<div class="t_btn"><a href="[field:typelink /]" class="mybtn">查看详情</a></div>
				</div>
			</div>
</div>
			<!--  <div class="ico_con">

    <ul>

      <li>{dede:type typeid='2'}<a href="[field:typelink /]">

        <div class="ico i1"><span><img src="/skin/images/ico_ppwzjs.gif" alt="我们·品牌网站建设专家" /></span></div>

        <p><strong>[field:typename /]</strong>Customized website</p>

        </a>