<?php
$z[0]=Array("typename","",0,18);
$z[1]=Array("typelink","",839,857);
$z[2]=Array("typename","",973,991);
$z[3]=Array("typelink","",1814,1832);
$z[4]=Array("typename","",1948,1966);
$z[5]=Array("typelink","",2789,2807);
$z[6]=Array("typename","",2923,2941);
$z[7]=Array("typelink","",3765,3783);
$z[8]=Array("typename","",3905,3923);
$z[9]=Array("typelink","",4747,4765);
$z[10]=Array("typelink","",4915,4933);
$z[11]=Array("typename","",5085,5103);

?>