<a href="[field:typelink /]"><div class="ico i1"><span><img src="/skin/images/ico_ppwzjs--.gif" alt="我们·品牌网站建设专家" /></span></div><p><strong>[field:typename /]</strong>Customized website</p></a></li>
      <li>{dede:type typeid='3'}<a href="[field:typelink /]"><div class="ico i2"><span><img src="/skin/images/ico_wmwzjs-.gif" alt="我们·外贸网站建设专家" /></span></div><p><strong>[field:typename /]</strong>Trade Website</p></a></li>
      <li>{dede:type typeid='4'}<a href="[field:typelink /]"><div class="ico i3"><span><img src="/skin/images/ico_ppyxx--.gif" alt="我们·品牌营销型专家" /></span></div><p><strong>[field:typename /]</strong>Marketing website building</p></a></li>
      <li>{dede:type typeid='5'}<a href="[field:typelink /]"><div class="ico i4"><span><img src="/skin/images/ico_scjs--.gif" width="218" height="140" alt="我们·商城建设专家" /></span></div><p><strong>[field:typename /]</strong>Enterprise Mall</p></a></li>
      <li>{dede:type typeid='6'}<a href="[field:typelink /]"><div class="ico i5"><span><img src="/skin/images/ico_wwz--.gif" alt="我们·微网站专家" /></span></div><p><strong>[field:typename /]</strong>Industry platform</p></a></li>
    </ul>
  </div>
  <div class="explain1"><h1>外贸网站建设</h1><em>根据目标客户的国家文化、浏览习惯等来设计网站架构</em><p>服务器、智能搜索引擎优化与灵活的后台操作系统相结合，以外贸网络营销理念为核心，<br />
将网络营销概念应用于外贸网站建设中。让您的外贸网站赢得Google、Yahoo等搜索引擎喜欢。</p></div>
</div>
<div class="nav"><a href="#tcpz"><span  data-icon="&#x69;"></span>套餐配置</a>               <a href="#"><span  data-icon="&#xe006;"></span>经典案例</a></div>
</div>

<div class="showcontent">
  
  <div class="trade_website" style="height:500px; padding-top:0px;">
<div class="box" style="height:530px; padding-top:0px;">
  <div class="container" style="height:453px; padding-top:0px;">
    <div class="img" style="height:460px; padding-top:0px;"><img src="/skin/images/wmwz_img.png" alt="我们提供外贸网站建设" /></div>
  </div>
  </div>
</div>
  
  <div class="configuration">
    <div class="tt" id="tcpz">套餐配置</div>
    <div class="box"><table width="100%" border="0" cellpadding="1" cellspacing="1" class="table1">
  <tr class="t1">
    <td width="80" align="center"><strong>特点</strong></td>
    <td>设计精美，功能性突出，重点在于企业宣传、客户服务和电子商务功能。从域名、网站空间、主页设计、应用软件开发、网站推广到电子商务，形成高级网站建设的完整解决方案。个性化的产品展示<br />
      系统及专业的在线订单系统，展示强大的公司实力。表现公司整体形象设计，整合公司企业的经营理念，获得更多的商机...</td>
  </tr>
  <tr class="t2">
    <td align="center"><strong>主机域名</strong></td>
    <td>
      <li><em data-icon="&#xe052;"></em>域名：可选国际或国内顶级英文域名一个， 例如：http://www.qizhu18.com</li>
      <li><em data-icon="&#xe052;"></em>空间：1000MB西部数云主机，月流量40GB(支持ASP、PHP、JSP、ASP.NET、ACCESS、MSSQL、MYSQL 数据库)</li>
      <li><em data-icon="&#xe052;"></em>邮箱：600MB可自主管理及分配的WEB企业邮局，支持POP、SMTP功能。可开通5个独立邮箱帐户</li>
      <li><em data-icon="&#xe052;"></em>网站开发语言：.NET    数据库： MSSQL</li>
      </td>
  </tr>
  <tr class="t1">
    <td align="center"><strong>栏目</strong></td>
    <td>
      <li><em data-icon="&#xe074;"></em>网站首页：首页设计突出公司形象、颜色、最新产品等功能，可选首页嵌入FLASH动画效果，进入中英文版本等功能 。</li>
      <li><em data-icon="&#xe058;"></em>公司介绍：公司/企业的全面介绍，企业文化、服务理念、规模介绍、厂房图片、资质认证、实力等方面的介绍。</li>
      <li><em data-icon="&#xe07a;"></em>产品展示：以图文形式介绍公司的主营产品、最新产品等信息，主营服务，服务范围（可选二级产品分类）。</li>
      <li><em data-icon="&#xe0f7;"></em>产品搜索：根据客户自身要求输入关键字在线搜索商品，更方便客户查找商品。</li>
      <li><em data-icon="&#xe08b;"></em>会员系统：会员可分等级(区分普通用户、VIP用户、代理商、加盟商)，更好保护产品设计及价格分级销售。</li>
      <li><em data-icon="&#xe059;"></em>新闻动态：发布公司最新信息动态、促销活动、招聘信息、行业新闻等内容。</li>
      <li><em data-icon="&#xe08a;"></em>人才招聘：通过自己公司网站发布公司招聘信息，提高形像，降低招聘成本，更有效地招聘到人才。</li>
      <li><em data-icon="&#xe05a;"></em>客户留言：方便客户通地互联网直接与客户沟通，接收订单，意见反馈等信息。大大降低销售成本。</li>
      <li><em data-icon="&#xe090;"></em>联系方式：让客户清楚了解公司相关联系方式，包括电话、地址、联系人，手机、银行帐号等。</li>
      <li><em data-icon="&#xe099;"></em>论坛博客：方便客户通地互联网直接商家间的沟通，接收订单，信息反馈等信息。大大提交平台的人气。</li>
      <li><em data-icon="&#xe00b;"></em>WAP建站：开通企业WAP网站，支持手机用户访问，内容包括网站首页、公司介绍、产品展示、新闻动态、人才招聘、</li>
      <li><em data-icon="&#xe018;"></em>客户留言、联系方式等WAP栏目。</li></td>
  </tr>
  <tr class="t2">
    <td align="center"><strong>应用模块</strong></td>
    <td>
      <li><em data-icon="&#xe052;"></em>客户留言系统：记录客户相关联系方式：公司名称、联系人、电话、手机、反馈意见、订单等信息。网站管理员可查 看所有客户留言记录。</li>
      <li><em data-icon="&#xe052;"></em>产品展示系统：可在线添加分类、产品、在线上传产品图片、自主添加、修改以及删除。提高信息发布时效，无需专 门的技术人员，减少相关制作人员的工作量，真正实现轻松、快捷、高效。</li>
      <li><em data-icon="&#xe052;"></em>会员管理系统：可查看、修改网站所有会员信息，会员等级、权限开通，产品/消息/报价的分级别加密。</li>
      <li><em data-icon="&#xe052;"></em>新闻发布系统：可在线添加新闻、自主修改以及删除。提高信息发布时效，无需专门的技术人员，减少相关制作人员 的工作量，真正实现轻松、快捷、高效。</li>
      <li><em data-icon="&#xe052;"></em>人才招聘系统：可在线发布招聘信息、自主添加、修改以及删除。提高信息招聘效率，无需专门的技术人员，减少相 关制作人员的工作量，真正实现轻松、快捷、高效。</li>
      <li><em data-icon="&#xe052;"></em>网站计数器系统：记录网站每天、每月、每年的的客户浏览数量、同时在线人数等信息。</li>
      <li><em data-icon="&#xe052;"></em>论坛博客系统：可查看、修改论坛博客所有会员信息，会员等级、权限开通，对会员发表的博文日志等进行审核批复等管理操作（增加Discuz另计费）</li>
    </td>
  </tr>
  <tr class="t1">
    <td align="center"><strong>售后服务</strong></td>
    <td>
      <li><em data-icon="&#xe052;"></em>一年内提供免费内容维护10页次（页面内容、文字修改，非需触动页面模板的情况下）</li>
      <li><em data-icon="&#xe052;"></em>网站运行监控、文件定期备份，保证客户资料不会丢失。</li>
      <li><em data-icon="&#xe052;"></em>企业网站应用和营销建议报告，提供年度网站流量报告。</li>
    </td>
  </tr>
  <tr class="t2">
    <td align="center"><strong>售后服务</strong></td>
    <td>
      <li><em data-icon="&#xe052;"></em>站点页面优化，搜索关键字优化，标准网站营销服务。</li>
      <li><em data-icon="&#xe052;"></em>供建站咨询报告，域名、网站名称设计。</li>
      <li><em data-icon="&#xe052;"></em>网站内容规划，最佳预算建议，最佳方案建议。</li>
      <li><em data-icon="&#xe052;"></em>域名注册/续费/解析/管理，网站虚拟主机空间开通/维护/管理。</li>
      <li><em data-icon="&#xe052;"></em>企业邮箱帐户开通/设置/管理，网站设计/制作/测试/发布全过程。</li>
      <li><em data-icon="&#xe052;"></em>访问量，独立IP，浏览量，浏览深度分析与技术支持。</li>
      <li><em data-icon="&#xe052;"></em>免费登陆国内著名搜索引擎（雅虎中国、Google、百度、中搜、一搜、搜狐）。提交ALEXA服务。</li>
      <li><em data-icon="&#xe052;"></em>免费ICP网站备案。</li>
    </td>
  </tr>
  <tr class="t1">
    <td align="center"><strong>制作周期</strong></td>
    <td>首页PSD（2-5个工作日）、子页（2-5个工作日）、前端（2-5个工作日）、程序（10个工作日）  具体确定方案后协商<br />
注：首页PSD、子页PSD阶段需根据客户确定时间另算，</td>
  </tr>
  <tr class="t2">
    <td align="center"><strong>备注</strong></td>
    <td>
      <li><em data-icon="&#xe052;"></em>支持多个语言版本开发、制作，如英文版、简体中文、繁体中文等。（每增加一个语言需增加总价费用30%）</li>
      <li><em data-icon="&#xe052;"></em>老客户网站改版和升级可享受9折优惠，老客户推荐的新客户有享受9折优惠。</li>
      <li><em data-icon="&#xe052;"></em>建站方案价格报价不含税，开发票外加6%个点。</li></td>
  </tr>
  <tr class="t1">
    <td align="center"><strong>价格</strong></td>
    <td>请咨询客服   QQ:888888   手机：13866666666</td>
  </tr>
</table>
</div>
  </div>
  
</div>
<div class="protection">
  <div class="container">
    <p><strong>做网站就是做<em>服务</em></strong></p>
    <p>网站做得好  还不够，我们提供一站式售后服务，全程由专业技术人员做您的售后工作。<br />
    业界良心 史无前例！</p>
    <div class="project">
      <ul>
        <li style="background-image: url(//skin/images/ico_service_01.gif);">全天候网站售后</li><li style="background-image: url(//skin/images/ico_service_02.gif);">即时在线沟通</li><li style="background-image: url(//skin/images/ico_service_04.gif);">网站安全防护</li><li style="background-image: url(//skin/images/ico_service_05.gif);">确保网站数据安全</li>
      </ul>
    </div>
  </div>
</div>
{dede:include filename="footer.htm"