<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1104,1139);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1210,1239);
$z[3][4]['name']="position";
$z[4]=Array("productimagelist","\r\n	<div class=\"box\"> <img src=\"[field:imgsrc/]\" width=\"880\" /> </div>\r\n	",1301,1420);
$z[5]=Array("field","",1462,1481);
$z[5][4]['name']="title";
$z[6]=Array("field","",1503,1525);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1553,1571);
$z[7][4]['name']="body";
$z[8]=Array("include","",1757,1794);
$z[8][4]['filename']="footer.htm";

?>