<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1104,1139);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1205,1234);
$z[3][4]['name']="position";
$z[4]=Array("productimagelist","\r\n	<div class=\"box\"> <img src=\"[field:imgsrc/]\" width=\"880\" /> </div>\r\n	",1296,1415);
$z[5]=Array("field","",1457,1476);
$z[5][4]['name']="title";
$z[6]=Array("field","",1498,1520);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1548,1566);
$z[7][4]['name']="body";
$z[8]=Array("include","",1745,1782);
$z[8][4]['filename']="footer.htm";

?>