<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",313,399);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",404,489);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",494,580);
$z[2][4]['typeid']="26";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",585,671);
$z[3][4]['typeid']="18";

?>