<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",301,387);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",392,477);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",482,568);
$z[2][4]['typeid']="26";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",573,659);
$z[3][4]['typeid']="18";

?>