<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",289,375);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",380,465);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",470,556);
$z[2][4]['typeid']="26";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",561,647);
$z[3][4]['typeid']="18";

?>