<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",303,389);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",394,479);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",484,570);
$z[2][4]['typeid']="26";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",575,661);
$z[3][4]['typeid']="18";

?>