<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",726,812);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1229,1314);
$z[1][4]['typeid']="7";
$z[2]=Array("channel","\r\n				<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n				",1359,1479);
$z[2][4]['row']="10";
$z[2][4]['typeid']="7";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1534,1620);
$z[3][4]['typeid']="26";
$z[4]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1656,1742);
$z[4][4]['typeid']="18";
$z[5]=Array("field","(@me==\"\")? @me=\"   class='current'  \":@me=\"\";",2112,2207);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channel","\r\n			<li><span><a href=\"[field:typelink/]\">[field:typename/]</a></span></li>\r\n			",2244,2463);
$z[6][4]['row']="7";
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><span><a class='current' href='~typelink~'>~typename~</a></span></li>";

?>