<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1325,1360);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1433,1462);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n	    <dd><a href=\"[field:typelink/]\">[field:typename/]</a></dd>\r\n		",1611,1793);
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<dd class=";
$z[4][4]['curr"><a href']="~typelink~";
$z[4][4]['>~typename~</a></dd>"']="";
$z[5]=Array("list","\r\n	<li>\r\n      <div class=\"newspic\"><a href=\"[field:arcurl/]\" title='[field:title/]'><img src=\"[field:picname/]\" width=\"176\" height=\"125\" border=\"0\" alt=\"[field:title/]\" /></a></div>\r\n      <a href=\"[field:arcurl/]\" title='[field:title/]'>[field:title/]…</a>\r\n      <p>[field:infos/]…</p>\r\n      <div class=\"time\">日期：[field:pubdate function=\"MyDate('Y/m/d',@me)\"/] 阅读：<em>[field:click/]</em></div>\r\n    </li>\r\n	",1943,2420);
$z[5][4]['pagesize']="8";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2486,2548);
$z[6][4]['listitem']="index,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2564,2601);
$z[7][4]['filename']="footer.htm";

?>