<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1398,1433);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," \r\n	  <span><a href=\"[field:typelink/]\">[field:typename/]</a></span>\r\n	  ",1562,1750);
$z[3][4]['row']="7";
$z[3][4]['currentstyle']="<span class=";
$z[3][4]['curr"><a href']="~typelink~";
$z[3][4]['>~typename~</a></span>"']="";
$z[4]=Array("list","\r\n	<li>\r\n      <div class=\"casepic\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"275\" height=\"305\" border=\"0\" /></a></div>\r\n      <div class=\"name\"><a href=\"[field:arcurl/]\">[field:title/]</a>\r\n        <p>[field:typelink/]</p>\r\n      </div>\r\n      <div class=\"brief\">[field:infos/]…</div>\r\n    </li>\r\n	",2480,2850);
$z[4][4]['pagesize']="8";
$z[4][4]['infolen']="100";
$z[5]=Array("pagelist","",2913,2975);
$z[5][4]['listitem']="index,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2991,3028);
$z[6][4]['filename']="footer.htm";

?>