<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",3892,3927);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","<a href=\"[field:typelink /]\">\r\n          <div class=\"ico i1\"><span><img src=\"/skin/images/ico_ppwzjs-.gif\" alt=\"我们·品牌网站建设专家\" /></span></div>\r\n          <p><strong>[field:typename /]</strong>Customized website</p>\r\n          </a>",4116,4399);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<a href=\"[field:typelink /]\">\r\n          <div class=\"ico i2\"><span><img src=\"/skin/images/ico_wmwzjs--.gif\" alt=\"我们·外贸网站建设专家\" /></span></div>\r\n          <p><strong>[field:typename /]</strong>Trade Website</p>\r\n          </a>",4418,4697);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<a href=\"[field:typelink /]\">\r\n          <div class=\"ico i3\"><span><img src=\"/skin/images/ico_ppyxx--.gif\" alt=\"我们·品牌营销型专家\" /></span></div>\r\n          <p><strong>[field:typename /]</strong>Marketing website building</p>\r\n          </a>",4716,5004);
$z[5][4]['typeid']="4";
$z[6]=Array("type","<a href=\"[field:typelink /]\">\r\n          <div class=\"ico i4\"><span><img src=\"/skin/images/ico_scjs--.gif\" width=\"218\" height=\"140\" alt=\"我们·商城建设专家\" /></span></div>\r\n          <p><strong>[field:typename /]</strong>Enterprise Mall</p>\r\n          </a>",5023,5321);
$z[6][4]['typeid']="5";
$z[7]=Array("type","<a href=\"[field:typelink /]\">\r\n          <div class=\"ico i5\"><span><img src=\"/skin/images/ico_wwz--.gif\" alt=\"我们·微网站专家\" /></span></div>\r\n          <p><strong>[field:typename /]</strong>Industry platform</p>\r\n          </a>",5340,5611);
$z[7][4]['typeid']="6";
$z[8]=Array("include","",15919,15956);
$z[8][4]['filename']="footer.htm";

?>