<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",331,360);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",400,458);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1475,1510);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel"," <span><a href=\"[field:typelink/]\">[field:typename/]</a></span> ",1634,1812);
$z[4][4]['row']="7";
$z[4][4]['currentstyle']="<span class=";
$z[4][4]['curr"><a href']="~typelink~";
$z[4][4]['>~typename~</a></span>"']="";
$z[5]=Array("global","",2668,2732);
$z[5][4]['name']="keyword";
$z[5][4]['function']="RemoveXSS(@me)";
$z[6]=Array("list","\r\n	<li>\r\n      <div class=\"casepic\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"275\" height=\"305\" border=\"0\" /></a></div>\r\n      <div class=\"name\"><a href=\"[field:arcurl/]\">[field:title/]</a>\r\n        <p>[field:typelink/]</p>\r\n      </div>\r\n      <div class=\"brief\">[field:infos/]…</div>\r\n    </li>\r\n	",2815,3185);
$z[6][4]['pagesize']="8";
$z[6][4]['infolen']="100";
$z[7]=Array("include","",3234,3271);
$z[7][4]['filename']="footer.htm";

?>