<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",3803,3838);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","[field:typename /]</h3>					<div class=\"yellowTipBox tcen\">经济实惠，简单小巧</div>					<div class=\"t_img\"><img src=\"http://img.dns.com.cn/host/host_pj.png\"></div>					<div class=\"t_cs\">						<table>							<tr>								<td class=\"ld\">操作系统：</td>								<td>Windows/Unix</td>							</tr>							<tr>								<td class=\"ld\">支持语言：</td>								<td>asp,php,html,htm等</td>							</tr>							<tr>								<td class=\"ld\">数据库：</td>								<td>MSSQL 50M或MYSQL 50M</td>							</tr>							<tr>								<td class=\"ld\">网页空间：</td>								<td>200M</td>							</tr>							<tr>								<td class=\"ld\">月流量：</td>								<td>无限制</td>							</tr>						</table>					</div>					<div class=\"t_price\"><span class=\"f20 red\">198</span>元/年</div>					<div class=\"t_btn\"><a href=\"[field:typelink /]\" class=\"mybtn\">查看详情</a></div>					",4081,4987);
$z[3][4]['typeid']="2";
$z[4]=Array("type","[field:typename /]</h3>					<div class=\"yellowTipBox tcen\">即开即用，方便快捷</div>					<div class=\"t_img\"><img src=\"http://img.dns.com.cn/host/host_bz.png\"></div>					<div class=\"t_cs\">						<table>							<tr>								<td class=\"ld\">操作系统：</td>								<td>Windows/Unix</td>							</tr>							<tr>								<td class=\"ld\">支持语言：</td>								<td>asp,php,html,htm等</td>							</tr>							<tr>								<td class=\"ld\">数据库：</td>								<td>MSSQL 100M或MYSQL 100M</td>							</tr>							<tr>								<td class=\"ld\">网页空间：</td>								<td>500M</td>							</tr>							<tr>								<td class=\"ld\">月流量：</td>								<td>无限制</td>							</tr>						</table>					</div>					<div class=\"t_price\"><span class=\"f20 red\">298</span>元/年</div>					<div class=\"t_btn\"><a href=\"[field:typelink /]\" class=\"mybtn\">查看详情</a></div>					",5039,5947);
$z[4][4]['typeid']="3";
$z[5]=Array("type","[field:typename /]</h3>					<div class=\"yellowTipBox tcen\">经济实惠，简单小巧</div>					<div class=\"t_img\"><img src=\"http://img.dns.com.cn/host/host_hk.png\"></div>					<div class=\"t_cs\">						<table>							<tr>								<td class=\"ld\">操作系统：</td>								<td>Windows/Unix</td>							</tr>							<tr>								<td class=\"ld\">支持语言：</td>								<td>asp,php,html,htm等</td>							</tr>							<tr>								<td class=\"ld\">数据库：</td>								<td>MSSQL 150M或MYSQL 150M</td>							</tr>							<tr>								<td class=\"ld\">网页空间：</td>								<td>800M</td>							</tr>							<tr>								<td class=\"ld\">月流量：</td>								<td>无限制</td>							</tr>						</table>					</div>					<div class=\"t_price\"><span class=\"f20 red\">398</span>元/年</div>					<div class=\"t_btn\"><a href=\"[field:typelink /]\" class=\"mybtn\">查看详情</a></div>					",5999,6907);
$z[5][4]['typeid']="4";
$z[6]=Array("type","[field:typename /]</h3>					<div class=\"yellowTipBox tcen\">即开即用，方便快捷</div>					<div class=\"t_img\"><img src=\"http://img.dns.com.cn/host/host_hk.png\"></div>					<div class=\"t_cs\">						<table>							<tr>								<td class=\"ld\">操作系统：</td>								<td>Windows/Unix</td>							</tr>							<tr>								<td class=\"ld\">支持语言：</td>								<td>asp,php,html,htm等</td>							</tr>							<tr>								<td class=\"ld\">数据库：</td>								<td>MSSQL 300M或MYSQL 300M</td>							</tr>							<tr>								<td class=\"ld\">网页空间：</td>								<td>1500M</td>							</tr>							<tr>								<td class=\"ld\">月流量：</td>								<td>无限制</td>							</tr>						</table>					</div>					<div class=\"t_price\"><span class=\"f20 red\">598</span>元/年</div>					<div class=\"t_btn\"><a href=\"[field:typelink /]\" class=\"mybtn\">查看详情</a></div>					",6959,7868);
$z[6][4]['typeid']="5";
$z[7]=Array("type","[field:typename /]</h3>					<div class=\"yellowTipBox tcen\">即开即用，方便快捷</div>					<div class=\"t_img\"><img src=\"http://img.dns.com.cn/host/host_hk.png\"></div>					<div class=\"t_cs\">						<table>							<tr>								<td class=\"ld\">操作系统：</td>								<td>Windows/Unix</td>							</tr>							<tr>								<td class=\"ld\">支持语言：</td>								<td>asp,php,html,htm等</td>							</tr>							<tr>								<td class=\"ld\">数据库：</td>								<td>MSSQL 300M或MYSQL 300M</td>							</tr>							<tr>								<td class=\"ld\">网页空间：</td>								<td>1500M</td>							</tr>							<tr>								<td class=\"ld\">月流量：</td>								<td>无限制</td>							</tr>						</table>					</div>					<div class=\"t_price\"><span class=\"f20 red\">598</span>元/年</div>					<div class=\"t_btn\"><a href=\"[field:typelink /]\" class=\"mybtn\">查看详情</a></div>					",7927,8836);
$z[7][4]['typeid']="6";
$z[8]=Array("type","<a href=\"[field:typelink /]\"><div class=\"ico i1\"><span><img src=\"/skin/images/ico_ppwzjs--.gif\" alt=\"我们·品牌网站建设专家\" /></span></div><p><strong>[field:typename /]</strong>Customized website</p></a>",8909,9157);
$z[8][4]['typeid']="2";
$z[9]=Array("type","<a href=\"[field:typelink /]\"><div class=\"ico i2\"><span><img src=\"/skin/images/ico_wmwzjs-.gif\" alt=\"我们·外贸网站建设专家\" /></span></div><p><strong>[field:typename /]</strong>Trade Website</p></a>",9173,9415);
$z[9][4]['typeid']="3";
$z[10]=Array("type","<a href=\"[field:typelink /]\"><div class=\"ico i3\"><span><img src=\"/skin/images/ico_ppyxx--.gif\" alt=\"我们·品牌营销型专家\" /></span></div><p><strong>[field:typename /]</strong>Marketing website building</p></a>",9431,9683);
$z[10][4]['typeid']="4";
$z[11]=Array("type","<a href=\"[field:typelink /]\"><div class=\"ico i4\"><span><img src=\"/skin/images/ico_scjs--.gif\" width=\"218\" height=\"140\" alt=\"我们·商城建设专家\" /></span></div><p><strong>[field:typename /]</strong>Enterprise Mall</p></a>",9699,9961);
$z[11][4]['typeid']="5";
$z[12]=Array("type","<a href=\"[field:typelink /]\"><div class=\"ico i5\"><span><img src=\"/skin/images/ico_wwz--.gif\" alt=\"我们·微网站专家\" /></span></div><p><strong>[field:typename /]</strong>Industry platform</p></a>",9977,10212);
$z[12][4]['typeid']="6";
$z[13]=Array("include","",19617,19654);
$z[13][4]['filename']="footer.htm";

?>